---
title: "NI03 InferCNV Analysis"
output: html_document
---

Install inferCNV. Instructions at https://github.com/broadinstitute/inferCNV/wiki/Installing_inferCNV and load packages
```{r}
# install GMD
# packageurl <- "https://cran.r-project.org/src/contrib/Archive/GMD/GMD_0.3.3.tar.gz"
# install.packages(packageurl, repos=NULL, type="source")
# NGHCM
# devtools::install_github("bmbroom/tsvio")
# devtools::install_github("bmbroom/NGCHMR", ref="stable")
# Install inferCNV from within R using BioConductor
if (!requireNamespace("BiocManager", quietly = TRUE))
     install.packages("BiocManager")
BiocManager::install("infercnv")
install.packages("nlme")
library(devtools)
library(phylogram)
library(gridExtra)
library(grid)
require(dendextend)
require(ggthemes)
library(tidyverse)
library(Seurat)
library(miscTools)
library(dendextend)
library(ggthemes)
```

```{r}
# rm(list=ls())
dir <- "/home/ubuntu/scell_lung_adenocarcinoma/"
# dir <- "/myVolume/scell_lung_adenocarcinoma/"
load(file=paste(dir,"Data_input/objects/NI02_Epi_Seurat_object_clustered.RData", sep=""))
load(file=paste(dir,"Data_input/objects/NI01_Nonimmune_Seurat_object_annotated.RData", sep=""))
```

Create and save a Raw Counts Table
```{r}
temp <- as.matrix(tiss_nonimmune@assays$RNA@counts)
write.table(x = temp, file =  paste(dir, "Data_input/objects/NI03_CNV_data_out_all_cells_raw_counts_largefile.txt", sep = ""), quote = F,sep = '\t')
rm(temp)
```

Create slim cell annotation file (malignant vs non-malignant) from Seurat object 
```{r}
# Epithelial cells 
temp.1 <- tiss_nonimmune_epi@meta.data[tiss_nonimmune_epi@meta.data$nonimmune_general_annotation %in% "epithelial", c("nonimmune_general_annotation","epi_seurat_cluster")] 
temp.1 <- cbind(as.data.frame(row.names(temp.1)), as.data.frame(do.call("paste",temp.1)))
colnames(temp.1) <- c("V1","V2")
# Endothelial cells and fibroblasts
temp.2 <- tiss_nonimmune@meta.data[tiss_nonimmune@meta.data$nonimmune_general_annotation %in% "endothelial", c("cell_id","nonimmune_general_annotation")]
colnames(temp.2) <- c("V1","V2")
temp.3 <- tiss_nonimmune@meta.data[tiss_nonimmune@meta.data$nonimmune_general_annotation %in% "fibroblast", c("cell_id","nonimmune_general_annotation")]
colnames(temp.3) <- c("V1","V2")
# Keep a total of 500 cells from both 
temp.2 <- temp.2[sample(nrow(temp.2), size = 800),]
temp.3<- temp.3[sample(nrow(temp.3), size = 800),]

# Convert some of the fibroblasts and endos to spikeins for the clustering 
temp.2$V2 <- paste(as.character(temp.2$V2), "_normal", sep="")
temp.2$V2[sample(which(temp.2$V2=="endothelial_normal"),300)] <- "endothelial"
temp.3$V2 <- paste(as.character(temp.3$V2), "_normal", sep="")
temp.3$V2[sample(which(temp.3$V2=="fibroblast_normal"),300)] <- "fibroblast"
# Combine 
inferCNV.annotation <- rbind(temp.1, temp.2, temp.3)
rm("temp.1", "temp.2", "temp.3")
# Write table
write.table(inferCNV.annotation, file = paste(dir,"Data_input/objects/NI03_CNV_cell_metadata_shuffle_largefile.txt", sep=""),row.names = F, col.names = F, quote=F, sep="\t")

table(inferCNV.annotation$V2)
```

Save all inferCNV files and run inferCNV in previous version of R

read in annotation data
```{r}
inferCNV.annotation.malignant <- read.csv(file = paste(dir, "data_out/NI03/results/inferCNV_annotation.csv", sep = ""), row.names = 1)
```


```{r}
# Add metadata inferCNV_annotation by cell_id
tiss_nonimmune_epi@meta.data <- left_join(x = tiss_nonimmune_epi@meta.data, y = inferCNV.annotation.malignant, by = "cell_id")

rownames(tiss_nonimmune_epi@meta.data) <- tiss_nonimmune_epi@meta.data$cell_id

#Save Seurat object 
save(tiss_nonimmune_epi, file = paste(dir, "Data_input/objects/NI03_epithelial_annotated_tumor.RData", sep = ""))

tiss_nonimmune@meta.data <- left_join(x = tiss_nonimmune@meta.data, y = inferCNV.annotation.malignant, by = "cell_id")
rownames(tiss_nonimmune@meta.data) <- tiss_nonimmune@meta.data$cell_id

#Save Seurat object 
save(tiss_nonimmune, file = paste(dir, "Data_input/objects/NI03_nonimmune_annotated_tumor.RData", sep = ""))
```


```{r}
table(tiss_subset_tumor2@meta.data$patient_id)
table(tiss_nonimmune_epi@meta.data$patient_id)
  
```


