---
title: "DE Analysis by Response"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(devtools)
library(ggsignif)
library(ggpubr)
library(viridis)
library(plotly)
library(ggridges)
library(reshape)
library(gridExtra)
library(ggrepel)
```

Read in tumor object
```{r}
# rm(list=ls())
dir <- "/myVolume/scell_lung_adenocarcinoma/"
load(file = paste(dir, "Data_input/NI04_tumor_seurat_object.RData", sep = ""))
```

```{r}
# set the ident of the object to the "analysis" column
unique(tiss_subset_tumor@ident) # check current ident
tiss_subset_tumor <- SetIdent(tiss_subset_tumor, ident.use = tiss_subset_tumor@meta.data$analysis)
unique(tiss_subset_tumor@ident) # check current ident
```

Calculate the pairwise comparisons between treatment groups of naive vs pr
```{r}
# calculate the pairwise comparision of naive vs pr
naive_v_pr <- FindMarkers(object = tiss_subset_tumor, ident.1 = "naive", ident.2 = "grouped_pr")
write.csv(naive_v_pr, file = paste(dir, "data_out/NI07/NI07_naive_v_pr_DEgenes.csv", sep = ""))
# naive_v_pr <- read.csv(file = paste(dir, "data_out/NI07/NI07_naive_v_pr_DEgenes.csv", sep = ""), row.names = 1)

# calculate the pairwise comparision of naive vs pd
naive_v_pd <- FindMarkers(object = tiss_subset_tumor, ident.1 = "naive", ident.2 = "grouped_pd")
write.csv(naive_v_pd, file = paste(dir, "data_out/NI07/NI07_naive_v_pd_DEgenes.csv", sep = ""))
# naive_v_pd <- read.csv(file = paste(dir, "data_out/NI07/NI07_naive_v_pd_DEgenes.csv", sep = ""), row.names = 1)

# calculate the pairwise comparision of pr vs pd
pr_v_pd <- FindMarkers(object = tiss_subset_tumor, ident.1 = "grouped_pr", ident.2 = "grouped_pd")
write.csv(pr_v_pd, file = paste(dir, "data_out/NI07/NI07_pr_v_pd_DEgenes.csv", sep = ""))
# pr_v_pd <- read.csv(file = paste(dir, "data_out/NI07/NI07_pr_v_pd_DEgenes.csv", sep = ""), row.names = 1)
```

To avoid patient specific effects, filter the DE list to exclude genes explained by a few patients
```{r}
# Group the DE genes and add the number of patients with nonzero expressing cells and the highest contributing patient's occupancy

# naive vs pr
naive_v_pr.1 <- naive_v_pr
groups <- c("naive", "grouped_pr")

for(i in 1:nrow(naive_v_pr.1)){
  # gene <- as.character(naive_v_pr.1$gene)[i]
  gene <- row.names(naive_v_pr.1)[i]
  gene.vec <- tiss_subset_tumor@data[gene,]
    for(j in 1:length(groups)){
      cells <- row.names(tiss_subset_tumor@meta.data)[which(tiss_subset_tumor@meta.data$analysis==groups[j])]
      all.no.zero.cells <- names(which(gene.vec[cells] !=0 )) # Set threshold
      tab.1 <- table(as.character(tiss_subset_tumor@meta.data[all.no.zero.cells,"patient_id"]))
      high.pat.per <- tab.1[which(tab.1==max(tab.1))[1]]/length(all.no.zero.cells)
      all.pat.length <- length(tab.1)
      naive_v_pr.1[i,paste(groups[j],"pt.occupancy")] <- high.pat.per
      naive_v_pr.1[i,paste(groups[j],"n.nonzero.pts")] <- all.pat.length
    }  
}
write.csv(naive_v_pr.1, file = paste(dir, "data_out/NI07/NI07_naive_v_pr_DEgenes_with_pt_occ.csv", sep = ""))
naive_v_pr.1 <- read.csv(file = paste(dir, "data_out/NI07/NI07_naive_v_pr_DEgenes_with_pt_occ.csv", sep = ""), row.names = 1)

# naive vs pd
naive_v_pd.1 <- naive_v_pd
groups <- c("naive", "grouped_pd")

for(i in 1:nrow(naive_v_pd.1)){
  # gene <- as.character(naive_v_pd.1$gene)[i]
  gene <- row.names(naive_v_pd.1)[i]
  gene.vec <- tiss_subset_tumor@data[gene,]
    for(j in 1:length(groups)){
      cells <- row.names(tiss_subset_tumor@meta.data)[which(tiss_subset_tumor@meta.data$analysis==groups[j])]
      all.no.zero.cells <- names(which(gene.vec[cells] !=0 )) # Set threshold
      tab.1 <- table(as.character(tiss_subset_tumor@meta.data[all.no.zero.cells,"patient_id"]))
      high.pat.per <- tab.1[which(tab.1==max(tab.1))[1]]/length(all.no.zero.cells)
      all.pat.length <- length(tab.1)
      naive_v_pd.1[i,paste(groups[j],"pt.occupancy")] <- high.pat.per
      naive_v_pd.1[i,paste(groups[j],"n.nonzero.pts")] <- all.pat.length
    }  
}
write.csv(naive_v_pd.1, file = paste(dir, "data_out/NI07/NI07_naive_v_pd_DEgenes_with_pt_occ.csv", sep = ""))
naive_v_pd.1 <- read.csv(file = paste(dir, "data_out/NI07/NI07_naive_v_pd_DEgenes_with_pt_occ.csv", sep = ""), row.names = 1)

# pr vs pd
pr_v_pd.1 <- pr_v_pd
groups <- c("grouped_pr", "grouped_pd")

for(i in 1:nrow(pr_v_pd.1)){
  # gene <- as.character(pr_v_pd.1$gene)[i]
  gene <- row.names(pr_v_pd.1)[i]
  gene.vec <- tiss_subset_tumor@data[gene,]
    for(j in 1:length(groups)){
      cells <- row.names(tiss_subset_tumor@meta.data)[which(tiss_subset_tumor@meta.data$analysis==groups[j])]
      all.no.zero.cells <- names(which(gene.vec[cells] !=0 )) # Set threshold
      tab.1 <- table(as.character(tiss_subset_tumor@meta.data[all.no.zero.cells,"patient_id"]))
      high.pat.per <- tab.1[which(tab.1==max(tab.1))[1]]/length(all.no.zero.cells)
      all.pat.length <- length(tab.1)
      pr_v_pd.1[i,paste(groups[j],"pt.occupancy")] <- high.pat.per
      pr_v_pd.1[i,paste(groups[j],"n.nonzero.pts")] <- all.pat.length
    }
}
write.csv(pr_v_pd.1, file = paste(dir, "data_out/NI07/NI07_pr_v_pd_DEgenes_with_pt_occ.csv", sep = ""))
pr_v_pd.1 <- read.csv(file = paste(dir, "data_out/NI07/NI07_pr_v_pd_DEgenes_with_pt_occ.csv", sep = ""), row.names = 1)
```

Naive vs PR plotting
```{r}
naive_v_pr.2 <- naive_v_pr.1
naive_v_pr.2$gene <- rownames(naive_v_pr.2)
naive_v_pr.2 <- filter(naive_v_pr.2, avg_logFC <= 0)
rownames(naive_v_pr.2) <- naive_v_pr.2$gene
# change avglogFC to positive number
naive_v_pr.2$avg_logFC <- naive_v_pr.2$avg_logFC * -1 
# filter out any genes that are explained by less than 6 patients contributing
hist(naive_v_pr.2$grouped_pr.n.nonzero.pts) # set threshold for 3 or more patients
naive_v_pr.2 <- filter(naive_v_pr.2, naive_v_pr.2$grouped_pr.n.nonzero.pts > 3)
rownames(naive_v_pr.2) <- naive_v_pr.2$gene
#Will have different colors depending on significance
mutateddf <- mutate(naive_v_pr.2, sig = ifelse(naive_v_pr.2$p_val_adj < 0.05, "p_val_adj<0.05", "NS")) 
rownames(mutateddf) <- mutateddf$gene
input_naive_pr <- mutateddf # input_naive_pr is sorted by pval_adjust
input_naive_pr.1 <- input_naive_pr[order(input_naive_pr$avg_logFC, decreasing = TRUE), ] # input_naive_pr.1 is sorted by avg_logFC
# save sorted gene lists
# write.csv(x = input_naive_pr.1, file = paste(dir, "data_out/NI07/NI07_pr_genes_prvnaive_analysis.csv", sep = ""))
volc = ggplot(input_naive_pr, aes(avg_logFC, -log10(p_val_adj))) + #volcanoplot with avg_logFC versus p_val_adj
    geom_point(aes(col=sig)) + #add points colored by significance
    scale_color_manual(values=c("black", "red")) + 
    ggtitle("Naive vs PR") 

naive_vs_pr_volc.1 <- volc + geom_text_repel(data=head(input_naive_pr.1, 20), aes(label=gene), point.padding = 1, box.padding = .3) +
  labs(y = expression(-log[10]*" "*"adjusted pvalue"), x = "avg log fold change") + 
  theme(legend.title = element_blank(), legend.position = "top") + 
  scale_fill_discrete(labels = c("Not Sig", "adjusted pval < 0.05"))
# save volcano plot
# ggsave(naive_vs_pr_volc.1, filename = paste(dir,"plot_out/NI07/NI07_naive_vs_pr_volcanoplot.pdf", sep=""), width = 15, height = 15)

pr.de.genes <- FetchData(tiss_subset_tumor, c(input_naive_pr.1$gene[1:50], 'nGene','nReads','analysis','patient_id', 'sample_name', 'biopsy_site', 'pfs_over_under'))
pr.de.genes1 <- colnames(pr.de.genes)[c(1:50)]
temp <- pr.de.genes[,c(grep("nGene", colnames(pr.de.genes)):ncol(pr.de.genes))]
# Plot ridge plot of pr vs PR vs naive for top 50 DE genes by patient
pr.plot.lists.ridge.pt <- list()
for(i in pr.de.genes1){
  a <- as.data.frame(pr.de.genes[,i])
  colnames(a) <- "gene"
  temp.4 <- cbind(a, temp) ; rm(a)
  pr.plot.lists.ridge.pt[[i]] <- ggplot(temp.4, aes(x = gene, y = analysis, fill = patient_id)) + geom_density_ridges(alpha=1/2) + theme(axis.title.y = element_blank()) + xlab(paste(i,"Gene Expression")) + guides(colour = FALSE, fill = FALSE) + scale_y_discrete(labels = c("Progressor", "Presister", "Naive"))
}
# save patient ridge plots
# pdf(file = paste(dir, "plot_out/NI07/NI07_naive_v_pr_rideplots_by_patient.pdf", sep = ""), onefile = TRUE)
# marrangeGrob(grobs=pr.plot.lists.ridge.pt, nrow=1, ncol=1)
# dev.off()
```

Naive vs PD plotting
```{r}
naive_v_pd.2 <- naive_v_pd.1
naive_v_pd.2$gene <- rownames(naive_v_pd.2)
naive_v_pd.2 <- filter(naive_v_pd.2, avg_logFC <= 0)
rownames(naive_v_pd.2) <- naive_v_pd.2$gene
# change avglogFC to positive number
naive_v_pd.2$avg_logFC <- naive_v_pd.2$avg_logFC * -1 
# filter out any genes that are explained by less than 6 patients contributing
hist(naive_v_pd.2$grouped_pd.n.nonzero.pts) # set threshold for 6 or more patients
naive_v_pd.2 <- filter(naive_v_pd.2, naive_v_pd.2$grouped_pd.n.nonzero.pts > 6)
rownames(naive_v_pd.2) <- naive_v_pd.2$gene
#Will have different colors depending on significance
mutateddf <- mutate(naive_v_pd.2, sig = ifelse(naive_v_pd.2$p_val_adj < 0.05, "p_val_adj<0.05", "NS")) 
rownames(mutateddf) <- mutateddf$gene
input_naive_pd <- mutateddf # input_naive_pd is sorted by pval_adjust
input_naive_pd.1 <- input_naive_pd[order(input_naive_pd$avg_logFC, decreasing = TRUE), ] # sorted by avglogFC
# save sorted gene lists
# write.csv(x = input_naive_pd.1, file = paste(dir, "data_out/NI07/NI07_pd_genes_pdvnaive_analysis.csv", sep = ""))
# create volcano plot
volc = ggplot(input_naive_pd, aes(avg_logFC, -log10(p_val_adj))) + #volcanoplot with avg_logFC versus p_val_adj
    geom_point(aes(col=sig)) + #add points colored by significance
    scale_color_manual(values=c("black", "red")) + 
    ggtitle("Naive vs PD") 

naive_vs_pd_volc.1 <- volc + geom_text_repel(data=head(input_naive_pd.1, 20), aes(label=gene), point.padding = 1, box.padding = .3) +
  labs(y = expression(-log[10]*" "*"adjusted pvalue"), x = "avg log fold change") + 
  theme(legend.title = element_blank(), legend.position = "top") + 
  scale_fill_discrete(labels = c("Not Sig", "adjusted pval < 0.05"))
# save volcano plot
# ggsave(naive_vs_pd_volc.1, filename = paste(dir,"plot_out/NI07/NI07_naive_vs_pd_volcanoplot.pdf", sep=""), width = 15, height = 15)

pd.de.genes <- FetchData(tiss_subset_tumor, c(input_naive_pd.1$gene[1:50], 'nGene','nReads','analysis','patient_id', 'sample_name', 'biopsy_site', 'pfs_over_under'))
pd.de.genes1 <- colnames(pd.de.genes)[c(1:50)]
temp <- pd.de.genes[,c(grep("nGene", colnames(pd.de.genes)):ncol(pd.de.genes))]
# Plot ridge plot of PD vs PR vs naive for top 50 DE genes by patient
pd.plot.lists.ridge.pt <- list()
for(i in pd.de.genes1){
  a <- as.data.frame(pd.de.genes[,i])
  colnames(a) <- "gene"
  temp.4 <- cbind(a, temp) ; rm(a)
  pd.plot.lists.ridge.pt[[i]] <- ggplot(temp.4, aes(x = gene, y = analysis, fill = patient_id)) + geom_density_ridges(alpha=1/2) + theme(axis.title.y = element_blank()) + xlab(paste(i,"Gene Expression")) + guides(colour = FALSE, fill = FALSE) + scale_y_discrete(labels = c("Progressor", "Presister", "Naive"))
}
# save patient ridge plots
# pdf(file = paste(dir, "plot_out/NI07/NI07_naive_v_pd_rideplots_by_patient.pdf", sep = ""), onefile = TRUE)
# marrangeGrob(grobs=pd.plot.lists.ridge.pt, nrow=1, ncol=1)
# dev.off()

# save IDO1 alone
ggsave(plot = pd.plot.lists.ridge.pt$IDO1, filename = paste(dir, "plot_out/NI07/NI07_IDO1.pdf", sep = ""))
# save CRABP2 alone
ggsave(plot = pd.plot.lists.ridge.pt$CRABP2, filename = paste(dir, "plot_out/NI07/NI07_CRABP2.pdf", sep = ""))
# save CRABP2 alone
ggsave(plot = pd.plot.lists.ridge.pt$GPR87, filename = paste(dir, "plot_out/NI07/NI07_GPR87.pdf", sep = ""))
```

PR vs PD plotting
```{r}
pr_v_pd.2 <- pr_v_pd.1
pr_v_pd.2$gene <- rownames(pr_v_pd.2)
#split the negative and positive avg_locFC
pr <- filter(pr_v_pd.2, avg_logFC > 0)
pd <- filter(pr_v_pd.2, avg_logFC < 0)
# add rownames back
rownames(pr) <- pr$gene
rownames(pd) <- pd$gene
# check the hist to set threshold for filtering out any genes that are explained by few number of patients
hist(pr$grouped_pr.n.nonzero.pts) # threshold at > 3 patients
hist(pd$grouped_pd.n.nonzero.pts) # threshold at > 6 patients
# set thresholds for 
pr <- filter(pr, pr$grouped_pr.n.nonzero.pts > 3)
rownames(pr) <- pr$gene
pd <- filter(pd, pd$grouped_pd.n.nonzero.pts > 6)
rownames(pd) <- pd$gene
# save pr and pd sorted by avglogFC
pr.1 <- pr[order(pr$avg_logFC, decreasing = TRUE), ]
pd.1 <- pd[order(pd$avg_logFC, decreasing = FALSE), ]
# rbind back together the pr and pd
pr_v_pd.3 <- rbind(pr, pd)
#Will have different colors depending on significance
mutateddf <- mutate(pr_v_pd.3, sig = ifelse(pr_v_pd.3$p_val_adj < 0.05, "p_val_adj<0.05", "NS")) 
rownames(mutateddf) <- mutateddf$gene
input_pr_pd <- mutateddf # input_pr_pd is sorted by pval_adjust
# save sorted gene lists
# write.csv(x = pr.1, file = paste(dir, "data_out/NI07/NI07_pr_genes_prvpd_analysis.csv", sep = ""))
# write.csv(x = pd.1, file = paste(dir, "data_out/NI07/NI07_pd_genes_prvpd_analysis.csv", sep = ""))
# sorted by avg_logFC
volc = ggplot(input_pr_pd, aes(avg_logFC, -log10(p_val_adj))) +
    geom_point(aes(col=sig)) + #add points colored by significance
    scale_color_manual(values=c("black", "red")) + 
    ggtitle("PR vs PD") 

pr_vs_pd_volc.1 <- volc + geom_text_repel(data=head(pr.1, 20), aes(label=gene), point.padding = 1, box.padding = .3) +
  geom_text_repel(data=head(pd.1, 20), aes(label=gene), point.padding = 1, box.padding = .3) +
  labs(y = expression(-log[10]*" "*"adjusted pvalue"), x = "avg log fold change") + 
  theme(legend.title = element_blank(), legend.position = "top") + 
  scale_fill_discrete(labels = c("Not Sig", "adjusted pval < 0.05"))
# save volcano plot
# ggsave(pr_vs_pd_volc.1, filename = paste(dir,"plot_out/NI07/NI07_pr_vs_pd_volcanoplot.pdf", sep=""), width = 15, height = 15)

pd_pr.de.genes <- FetchData(tiss_subset_tumor, c(pr.1$gene[1:25], pd.1$gene[1:25], 'nGene','nReads','analysis','patient_id', 'sample_name', 'biopsy_site', 'pfs_over_under'))
pd_pr.de.genes1 <- colnames(pd_pr.de.genes)[c(1:50)]
temp <- pd_pr.de.genes[,c(grep("nGene", colnames(pd_pr.de.genes)):ncol(pd_pr.de.genes))]
# Plot ridge plot of PD vs PR vs naive for top 50 DE genes by patient
pd.pr.plot.lists.ridge.pt <- list()
for(i in pd_pr.de.genes1){
  a <- as.data.frame(pd_pr.de.genes[,i])
  colnames(a) <- "gene"
  temp.4 <- cbind(a, temp) ; rm(a)
  pd.pr.plot.lists.ridge.pt[[i]] <- ggplot(temp.4, aes(x = gene, y = analysis, fill = patient_id)) + geom_density_ridges(alpha=1/2) + theme(axis.title.y = element_blank()) + xlab(paste(i,"Gene Expression")) + guides(colour = FALSE, fill = FALSE) + scale_y_discrete(labels = c("Progressor", "Presister", "Naive"))
}
# save patient ridge plots
# pdf(file = paste(dir, "plot_out/NI07/NI07_pr_v_pd_rideplots_by_patient.pdf", sep = ""), onefile = TRUE)
# marrangeGrob(grobs=pd.plot.lists.ridge.pt, nrow=1, ncol=1)
# dev.off()

ggsave(pd.pr.plot.lists.ridge.pt$SUSD2, filename = paste(dir, "plot_out/NI07/NI07_SUSD2.pdf", sep = ""))
ggsave(pd.pr.plot.lists.ridge.pt$PDE4C, filename = paste(dir, "plot_out/NI07/NI07_PDE4C.pdf", sep = ""))
ggsave(pd.pr.plot.lists.ridge.pt$DKK1, filename = paste(dir, "plot_out/NI07/NI07_DKK1.pdf", sep = ""))
ggsave(pd.pr.plot.lists.ridge.pt$GJB3, filename = paste(dir, "plot_out/NI07/NI07_GJB3.pdf", sep = ""))
```


Create a Heatmap of the top genes identified different between the groups
```{r}
# genes from navie vs pr/pd
naive_v_pr_pd_genes <- unique(c(input_naive_pr.1$gene[1:20], input_naive_pd.1$gene[1:20]))
# genes from pr vs pd
pr_v_pd_genes <- unique(c(pr.1$gene[1:20], pd.1$gene[1:20]))
# all identified genes
all_id_genes <- unique(c(naive_v_pr_pd_genes, pr_v_pd_genes))
write.csv(x = all_id_genes, file = paste(dir, "data_out/NI07/NI07_topgenes_id.csv", sep = ""))
# check ident
unique(tiss_subset_tumor@ident)
# change ident to analysis group
tiss_subset_tumor <- SetIdent(tiss_subset_tumor, ident.use = tiss_subset_tumor@meta.data$analysis)
# save heatmap of genes
pdf(file = paste(dir, "plot_out/NI07/NI07_top20_DEgenes_per_group.pdf", sep=""))
DoHeatmap(tiss_subset_tumor, genes.use = all_id_genes, slim.col.label = TRUE, use.scaled = FALSE, group.order = c("naive", "grouped_pr", "grouped_pd"))
dev.off()
# changes from naive to pr/pd
pdf(file = paste(dir, "plot_out/NI07/NI07_top20_DEgenes_naive_to_pr_pd.pdf", sep=""))
DoHeatmap(tiss_subset_tumor, genes.use = naive_v_pr_pd_genes, slim.col.label = TRUE, use.scaled = FALSE, group.order = c("naive", "grouped_pr", "grouped_pd"))
dev.off()
# changes between pr and pd
pdf(file = paste(dir, "plot_out/NI07/NI07_top20_DEgenes_pr_vs_pd.pdf", sep=""))
DoHeatmap(tiss_subset_tumor, genes.use = pr_v_pd_genes, slim.col.label = TRUE, use.scaled = FALSE, group.order = c("naive", "grouped_pr", "grouped_pd"))
dev.off()
```

