---
title: "Bulkize by Sample"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
```

Read in tumor object
```{r}
# rm(list=ls())
dir <- "/myVolume/scell_lung_adenocarcinoma/"
load(file = paste(dir, "Data_input/objects/NI04_tumor_seurat_object.RData", sep = ""))
```


```{r}
PER_cells <- filter(tiss_subset_tumor2@meta.data, analysis == "grouped_pr")
PER_samples <- SubsetData(object = tiss_subset_tumor2, PER_cells$cell_id)
head(tiss_subset_tumor2@meta.data)
table(PER_samples@meta.data$sample_name)
per_sample_names <- unique(PER_samples@meta.data$sample_name)
```

```{r}
PER_samples <- SetIdent(PER_samples, ident.use = PER_samples@meta.data$sample_name)
table(PER_samples@ident)
per.sample.averages <- AverageExpression(object = PER_samples)
```

```{r}
Alveolar_sig <- c("SFTPC", "SFTPB", "SFTPD", "PGC", "CLDN18", "AQP4", "SCGB3A1", "ABCA3", "GATA6", "NKX2-1", "SFTA3", "IGFBP2", "HOPX", "NAPSA", "FOXA2", "AGER", "LAMP1")
PER_Alveolar <- per.sample.averages[Alveolar_sig, ]
PER_Alveolar_mean <- colMeans(PER_Alveolar)
```

```{r}
table(PER_samples@meta.data$sample_name, PER_samples@meta.data$pfs_over_under)
```


```{r}
Kynurenine_sig <- c('IDO1', 'KYNU', 'QPRT')
PER_Kynurenine <- per.sample.averages[Kynurenine_sig, ]
PER_Kynurenine_mean <- colMeans(PER_Kynurenine)
```

```{r}
Plasminogen_sig <- c('ANXA2', 'PLAT', 'PLAU', 'PLAUR')
PER_Plasminogen <- per.sample.averages[Plasminogen_sig, ]
PER_Plasminogen_mean <- colMeans(PER_Plasminogen)
```

```{r}
Serpine_sig <-  per.sample.averages["SERPINE1", ]
```

```{r}
GapJunction_sig <- c('GJB3', 'GJB2', 'GJB4','GJB5')
PER_GapJunction <- per.sample.averages[GapJunction_sig, ]
PER_GapJunction_mean <- colMeans(PER_GapJunction)
```




