---
title: "TCGA Survival Analysis"
output: html_notebook
---

```{r}
library(survival)
library(survminer)
library(dplyr)
library(tidyverse)
```

Read in TCGA data
```{r}
# rm(list=ls())
dir <- "/home/ubuntu/scell_lung_adenocarcinoma/"
luad_tcga <- read.csv(file = paste(dir, "Data_input/TCGA/tcga_luad_counts.csv", sep = ""))
tcga_meta <- read.csv(file = paste(dir, "Data_input/TCGA/tcga_luad_metadata.csv", sep = ""), row.names = 1)
CIBERSORT_tcga <- read.csv(file = paste(dir, "Data_input/TCGA/CIBERSORT_TCGA.csv", sep = ""))
```

Investigate colnames and data structure
```{r}
dim(luad_tcga)
dim(tcga_meta)
head(luad_tcga)
head(tcga_meta)
```

Subset and format TCGA data
```{r}
tcga_samples <- as.data.frame(colnames(luad_tcga))
tcga_samples1 <- data.frame(do.call('rbind', strsplit(as.character(tcga_samples$`colnames(luad_tcga)`),'.',fixed=TRUE)))
tcga_samples1 <- tcga_samples1[(2:586),]
table(tcga_samples1$X4) #subset to only 01A tcga samples
tcga_samples1 <- filter(tcga_samples1, X4 == "01A")
tcga_samples1$name <- paste(tcga_samples1$X1, tcga_samples1$X2, tcga_samples1$X3, tcga_samples1$X4, sep = ".")
tcga_samples1$bcr_patient_barcode <- paste(tcga_samples1$X1, tcga_samples1$X2, tcga_samples1$X3, sep = "-")

#subset luad_tcga to tcga_samples1$name
luad_tcga <- luad_tcga[, c("gene", tcga_samples1$name)]
#subset luad_tcga to genes not duplicated, set rownames to genes
n_occur <- data.frame(table(luad_tcga$gene))
genes_remove <- luad_tcga[luad_tcga$gene %in% n_occur$Var1[n_occur$Freq > 1],]
luad_tcga1 <- luad_tcga[ ! luad_tcga$gene %in% genes_remove$gene, ]
rownames(luad_tcga1) <- luad_tcga1$gene
luad_tcga1$gene <- NULL
head(luad_tcga1)

#gsub the "." in colnames to "-"
colnames(luad_tcga1) <- gsub(pattern = "\\.", replacement = "-", x = colnames(luad_tcga1))

#gsub the "-01A" to the end of the bcr sample name
tcga_meta$bcr_patient_barcode <- paste(tcga_meta$bcr_patient_barcode, "-01A", sep = "")
head(tcga_meta)
head(luad_tcga1)
```

Example output with TCGA, a simple example
```{r}
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv(OS.time, OS) ~ gender, data = tcga_meta), 
    xlab = "Days",
    ylab = "Overall survival probability",
    legend.title = "Rx Group",
    censor = TRUE,
    pval = TRUE)
```

```{r}
Alveolar_sig <- c("SFTPC", "SFTPB", "SFTPD", "PGC", "CLDN18", "AQP4", "SCGB3A1", "ABCA3", "GATA6", "NKX2-1", "SFTA3", "IGFBP2", "HOPX", "NAPSA", "FOXA2", "AGER", "LAMP1")
TCGA_Alveolar <- luad_tcga1[Alveolar_sig, ]
head(TCGA_Alveolar)
dim(TCGA_Alveolar)
TCGA_Alveolar_mean <- as.data.frame(colMeans(TCGA_Alveolar))
colnames(TCGA_Alveolar_mean) <- "TCGA_Alveolar_mean"
hist(TCGA_Alveolar_mean$TCGA_Alveolar_mean)
summary(TCGA_Alveolar_mean$TCGA_Alveolar_mean)
TCGA_Alveolar_mean$Alveolar_quartile <- ntile(TCGA_Alveolar_mean$TCGA_Alveolar_mean, 4)  
TCGA_Alveolar_mean$bcr_patient_barcode <- rownames(TCGA_Alveolar_mean)
```

```{r}
TCGA_Alveolar_mean_f <- TCGA_Alveolar_mean
TCGA_Alveolar_mean_f$Alveolar_quartile.1 <- TCGA_Alveolar_mean_f$Alveolar_quartile
# TCGA_Alveolar_mean_f$Alveolar_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_Alveolar_mean_f$Alveolar_quartile.1)
table(TCGA_Alveolar_mean_f$Alveolar_quartile.1)
```


```{r}
luad_tcga1_AlveolarSig <- left_join(tcga_meta, TCGA_Alveolar_mean_f, by = "bcr_patient_barcode")
head(luad_tcga1_AlveolarSig)

#subset to only stage III and IV
# luad_tcga1_AlveolarSig <- filter(luad_tcga1_AlveolarSig, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")

# Use only quantile 1 and 4
# luad_tcga1_AlveolarSig <- filter(luad_tcga1_AlveolarSig, Alveolar_quartile.1 == "1" | Alveolar_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/Alveolar_Sig_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ Alveolar_quartile.1, data = luad_tcga1_AlveolarSig), 
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "Alveolar Expression Signature",
    censor = TRUE,
    pval = TRUE,
    conf.int = FALSE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ Alveolar_quartile.1, data = luad_tcga1_AlveolarSig)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  Alveolar_quartile.1, data = luad_tcga1_AlveolarSig), 
#         times = 2)
# 
# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ Alveolar_quartile.1, data = luad_tcga1_AlveolarSig), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "Alveolar Expression Signature",
#     censor = TRUE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))
# 
# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  Alveolar_quartile.1, data = luad_tcga1_AlveolarSig), 
#         times = 2)
```

```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = Alveolar_quartile$OS.time, event = Alveolar_quartile$OS)
surv_object

luad_tcga1_AlveolarSig$Kynurenine_quartile.1 <- factor(luad_tcga1_AlveolarSig$Kynurenine_quartile.1)

# Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ Alveolar_quartile,
                   data = luad_tcga1_AlveolarSig, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_AlveolarSig)

summary(fit.coxph)
```

```{r}
Kynurenine_sig <- c('IDO1', 'KYNU', 'QPRT')
TCGA_Kynurenine <- luad_tcga1[Kynurenine_sig, ]
head(TCGA_Kynurenine)
TCGA_Kynurenine_mean <- as.data.frame(colMeans(TCGA_Kynurenine))
colnames(TCGA_Kynurenine_mean) <- "TCGA_Kynurenine_mean"
hist(TCGA_Kynurenine_mean$TCGA_Kynurenine_mean)
summary(TCGA_Kynurenine_mean$TCGA_Kynurenine_mean)
TCGA_Kynurenine_mean$Kynurenine_quartile <- ntile(TCGA_Kynurenine_mean$TCGA_Kynurenine_mean, 4)  
TCGA_Kynurenine_mean$bcr_patient_barcode <- rownames(TCGA_Kynurenine_mean)
```

```{r}
TCGA_Kynurenine_mean_f <- TCGA_Kynurenine_mean
TCGA_Kynurenine_mean_f$Kynurenine_quartile.1 <- TCGA_Kynurenine_mean_f$Kynurenine_quartile
# TCGA_Kynurenine_mean_f$Kynurenine_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_Kynurenine_mean_f$Kynurenine_quartile.1)
table(TCGA_Kynurenine_mean_f$Kynurenine_quartile.1)
```

```{r}
luad_tcga1_Kynurenine <- left_join(tcga_meta, TCGA_Kynurenine_mean_f, by = "bcr_patient_barcode")

# subset to late stage
# luad_tcga1_Kynurenine <- filter(luad_tcga1_Kynurenine, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")
# table(luad_tcga1_Kynurenine$ajcc_pathologic_tumor_stage)

# Use only quantile 1 and 4
# luad_tcga1_Kynurenine <- filter(luad_tcga1_Kynurenine, Kynurenine_quartile.1 == "1" | Kynurenine_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/Kynurenine_Sig_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ Kynurenine_quartile.1, data = luad_tcga1_Kynurenine), 
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "Kynurenine Expression Quartiles",
    censor = TRUE,
    pval = TRUE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ Kynurenine_quartile.1, data = luad_tcga1_Kynurenine)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  Kynurenine_quartile.1, data = luad_tcga1_Kynurenine), times = 3)

# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ Kynurenine_quartile.1, data = luad_tcga1_Kynurenine), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "Kynurenine Expression Quartiles",
#     censor = TRUE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))

# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  Kynurenine_quartile.1, data = luad_tcga1_Kynurenine), 
#         times = 3)
```

```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = luad_tcga1_Kynurenine$OS.time, event = luad_tcga1_Kynurenine$OS)
surv_object

luad_tcga1_Kynurenine$Kynurenine_quartile.1 <- factor(luad_tcga1_Kynurenine$Kynurenine_quartile.1)

# 
# # Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ Kynurenine_quartile.1,
                   data = luad_tcga1_Kynurenine, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_Kynurenine)

summary(fit.coxph)
```



```{r}
Plasminogen_sig <- c('ANXA2', 'PLAT', 'PLAU', 'PLAUR')
TCGA_Plasminogen <- luad_tcga1[Plasminogen_sig, ]
head(TCGA_Plasminogen)
TCGA_Plasminogen_mean <- as.data.frame(colMeans(TCGA_Plasminogen))
colnames(TCGA_Plasminogen_mean) <- "TCGA_Plasminogen_mean"
hist(TCGA_Plasminogen_mean$TCGA_Plasminogen_mean)
summary(TCGA_Plasminogen_mean$TCGA_Plasminogen_mean)
TCGA_Plasminogen_mean$Plasminogen_quartile <- ntile(TCGA_Plasminogen_mean$TCGA_Plasminogen_mean, 4)
TCGA_Plasminogen_mean$bcr_patient_barcode <- rownames(TCGA_Plasminogen_mean)
```

```{r}
TCGA_Plasminogen_mean_f <- TCGA_Plasminogen_mean
TCGA_Plasminogen_mean_f$Plasminogen_quartile.1 <- TCGA_Plasminogen_mean_f$Plasminogen_quartile
# TCGA_Plasminogen_mean_f$Plasminogen_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_Plasminogen_mean_f$Plasminogen_quartile.1)
table(TCGA_Plasminogen_mean_f$Plasminogen_quartile.1)
```

```{r}
luad_tcga1_Plasminogen <- left_join(tcga_meta, TCGA_Plasminogen_mean_f, by = "bcr_patient_barcode")

# Subset to only late stage
# luad_tcga1_Plasminogen <- filter(luad_tcga1_Plasminogen, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")
# table(luad_tcga1_Plasminogen$ajcc_pathologic_tumor_stage)

# Use only quantile 1 and 4
# luad_tcga1_Plasminogen <- filter(luad_tcga1_Plasminogen, Plasminogen_quartile.1 == "1" | Plasminogen_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/Plasminogen_Sig_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ Plasminogen_quartile.1, data = luad_tcga1_Plasminogen),
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "Plasminogen Expression Quartiles",
    censor = TRUE,
    pval = TRUE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ Plasminogen_quartile.1, data = luad_tcga1_Plasminogen)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  Plasminogen_quartile.1, data = luad_tcga1_Plasminogen), censored = T)
# 
# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ Plasminogen_quartile.1, data = luad_tcga1_Plasminogen), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "Plasminogen Expression Quartiles",
#     censor = TRUE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))
# 
# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  Plasminogen_quartile.1, data = luad_tcga1_Plasminogen), 
#         times = 3)
```

```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = luad_tcga1_Plasminogen$OS.time, event = luad_tcga1_Plasminogen$OS)
surv_object

luad_tcga1_Plasminogen$Plasminogen_quartile.1 <- factor(luad_tcga1_Plasminogen$Plasminogen_quartile.1)

# 
# # Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ Plasminogen_quartile.1,
                   data = luad_tcga1_Plasminogen, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_Plasminogen)

summary(fit.coxph)
```


```{r}
Serpine_sig <-  luad_tcga1["SERPINE1", ]
TCGA_Serpine_sig <- as.data.frame(t(Serpine_sig))
colnames(TCGA_Serpine_sig) <- "TCGA_SERPINE1"
hist(TCGA_Serpine_sig$TCGA_SERPINE1)
summary(TCGA_Serpine_sig$TCGA_SERPINE1)
TCGA_Serpine_sig$SERPINE1_quartile <- ntile(TCGA_Serpine_sig$TCGA_SERPINE1, 4)
TCGA_Serpine_sig$bcr_patient_barcode <- rownames(TCGA_Serpine_sig)
```

```{r}
TCGA_Serpine_sig_f <- TCGA_Serpine_sig
TCGA_Serpine_sig_f$SERPINE1_quartile.1 <- TCGA_Serpine_sig_f$SERPINE1_quartile
# TCGA_Serpine_sig_f$SERPINE1_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_Serpine_sig_f$SERPINE1_quartile.1)
table(TCGA_Serpine_sig_f$SERPINE1_quartile.1)
```


```{r}
luad_tcga1_Serpine <- left_join(tcga_meta, TCGA_Serpine_sig_f, by = "bcr_patient_barcode")

# Subset to only lage stage
# luad_tcga1_Serpine <- filter(luad_tcga1_Serpine, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")
# table(luad_tcga1_Serpine$ajcc_pathologic_tumor_stage)

# Use only quantile 1 and 4
# luad_tcga1_Serpine <- filter(luad_tcga1_Serpine, SERPINE1_quartile.1 == "1" | SERPINE1_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/SERPINE1_Sig_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ SERPINE1_quartile.1, data = luad_tcga1_Serpine), 
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "SERPINE1 Expression Quartiles",
    censor = TRUE,
    pval = TRUE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ SERPINE1_quartile.1, data = luad_tcga1_Serpine)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  SERPINE1_quartile.1, data = luad_tcga1_Serpine), 
#         times = 3)
# 
# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ SERPINE1_quartile.1, data = luad_tcga1_Serpine), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "SERPINE1 Expression Quartiles",
#     censor = TRUE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))
# 
# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  SERPINE1_quartile.1, data = luad_tcga1_Serpine), 
#         times = 3)
```

```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = luad_tcga1_Serpine$OS.time, event = luad_tcga1_Serpine$OS)
surv_object

luad_tcga1_Serpine$SERPINE1_quartile.1 <- factor(luad_tcga1_Serpine$SERPINE1_quartile.1)

# 
# # Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ SERPINE1_quartile.1,
                   data = luad_tcga1_Serpine, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_Serpine)

summary(fit.coxph)
```

```{r}
GapJunction_sig <- c('GJB3', 'GJB2','GJB5')
TCGA_GapJunction <- luad_tcga1[GapJunction_sig, ]
head(TCGA_GapJunction)
TCGA_GapJunction_mean <- as.data.frame(colMeans(TCGA_GapJunction))
colnames(TCGA_GapJunction_mean) <- "TCGA_GapJunction_mean"
hist(TCGA_GapJunction_mean$TCGA_GapJunction_mean)
summary(TCGA_GapJunction_mean$TCGA_GapJunction_mean)
TCGA_GapJunction_mean$GapJunction_quartile <- ntile(TCGA_GapJunction_mean$TCGA_GapJunction_mean, 4)
TCGA_GapJunction_mean$bcr_patient_barcode <- rownames(TCGA_GapJunction_mean)
```

```{r}
TCGA_GapJunction_mean_f <- TCGA_GapJunction_mean
TCGA_GapJunction_mean_f$GapJunction_quartile.1 <- TCGA_GapJunction_mean_f$GapJunction_quartile
# TCGA_GapJunction_mean_f$GapJunction_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_GapJunction_mean_f$GapJunction_quartile.1)
table(TCGA_GapJunction_mean_f$GapJunction_quartile.1)
```

```{r}
luad_tcga1_GapJunction <- left_join(tcga_meta, TCGA_GapJunction_mean_f, by = "bcr_patient_barcode")

# Subset to only late stage
# luad_tcga1_GapJunction <- filter(luad_tcga1_GapJunction, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")
# table(luad_tcga1_GapJunction$ajcc_pathologic_tumor_stage)

# Use only quantile 1 and 4
# luad_tcga1_GapJunction <- filter(luad_tcga1_GapJunction, GapJunction_quartile.1 == "1" | GapJunction_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/GapJunction_Sig_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ GapJunction_quartile.1, data = luad_tcga1_GapJunction),
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "Gap Junciton Expression Quartile",
    censor = TRUE,
    conf.int = FALSE,
    pval = TRUE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ GapJunction_quartile.1, data = luad_tcga1_GapJunction)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  GapJunction_quartile.1, data = luad_tcga1_GapJunction), 
#         times = 3)
# 
# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ GapJunction_quartile.1, data = luad_tcga1_GapJunction), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "Gap Junciton Expression Quartile",
#     censor = TRUE,
#     conf.int = FALSE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))
# 
# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  GapJunction_quartile.1, data = luad_tcga1_GapJunction), 
#         times = 3)
summary(survival::survfit(survival::Surv((OS.time/365), OS) ~ GapJunction_quartile.1, data = luad_tcga1_GapJunction))
```

```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = luad_tcga1_GapJunction$OS.time, event = luad_tcga1_GapJunction$OS)
surv_object

luad_tcga1_GapJunction$GapJunction_quartile.1 <- factor(luad_tcga1_GapJunction$GapJunction_quartile.1)

# 
# # Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ GapJunction_quartile.1,
                   data = luad_tcga1_GapJunction, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_GapJunction)

summary(fit.coxph)
```


```{r}
colnames(CIBERSORT_tcga)
macrophages <- c("Monocytes", "Macrophages.M0", "Macrophages.M1", "Macrophages.M2")
t_cell <- c("T.cells.CD8", "T.cells.CD4.naive", "T.cells.CD4.memory.resting", "T.cells.CD4.memory.activated", "T.cells.follicular.helper", "T.cells.regulatory..Tregs.", "T.cells.gamma.delta", "NK.cells.resting", "NK.cells.activated")
```

CIBERSORT MACROPHAGES
```{r}
TCGA_Macrophages <- CIBERSORT_tcga[, c(macrophages, "Input.Sample")]
head(TCGA_Macrophages)
TCGA_Macrophages$TCGA_Macrophages_sum <- rowSums(TCGA_Macrophages[1:4])
summary(TCGA_Macrophages$TCGA_Macrophages_sum)
TCGA_Macrophages$Macrophages_quartile <- ntile(TCGA_Macrophages$TCGA_Macrophages_sum, 4)
TCGA_Macrophages$bcr_patient_barcode <- rownames(TCGA_Macrophages)

TCGA_Macrophages_f <- TCGA_Macrophages
TCGA_Macrophages_f$Macrophages_quartile.1 <- TCGA_Macrophages_f$Macrophages_quartile
# TCGA_Macrophages_f$Macrophages_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_Macrophages_f$Macrophages_quartile.1)
table(TCGA_Macrophages_f$Macrophages_quartile.1)
TCGA_Macrophages_f$bcr_patient_barcode <- TCGA_Macrophages$Input.Sample

luad_tcga1_Macrophages <- left_join(tcga_meta, TCGA_Macrophages_f, by = "bcr_patient_barcode")

# Subset to only late stage
# luad_tcga1_Macrophages <- filter(luad_tcga1_Macrophages, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")
# table(luad_tcga1_Macrophages$ajcc_pathologic_tumor_stage)

# Use only quantile 1 and 4
# luad_tcga1_Macrophages <- filter(luad_tcga1_Macrophages, Macrophages_quartile.1 == "1" | Macrophages_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/Macrophage_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ Macrophages_quartile.1, data = luad_tcga1_Macrophages),
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "Macrophage Population Quartile",
    censor = TRUE,
    conf.int = FALSE,
    pval = TRUE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ Macrophages_quartile.1, data = luad_tcga1_Macrophages)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  Macrophages_quartile.1, data = luad_tcga1_Macrophages), 
#         times = 3)
# 
# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ Macrophages_quartile.1, data = luad_tcga1_Macrophages), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "Macrophage Population Quartile",
#     censor = TRUE,
#     conf.int = FALSE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))
# 
# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  Macrophages_quartile.1, data = luad_tcga1_Macrophages), 
#         times = 3)
```

```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = luad_tcga1_Macrophages$OS.time, event = luad_tcga1_Macrophages$OS)
surv_object

luad_tcga1_Macrophages$Macrophages_quartile.1 <- factor(luad_tcga1_Macrophages$Macrophages_quartile.1)

# 
# # Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ Macrophages_quartile.1,
                   data = luad_tcga1_Macrophages, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_Macrophages)

summary(fit.coxph)
```

```{r}
TCGA_t_cells <- CIBERSORT_tcga[, c(t_cell, "Input.Sample")]
head(TCGA_t_cells)
TCGA_t_cells$TCGA_t_cells_sum <- rowSums(TCGA_t_cells[1:4])
summary(TCGA_t_cells$TCGA_t_cells_sum)
TCGA_t_cells$t_cells_quartile <- ntile(TCGA_t_cells$TCGA_t_cells_sum, 4)
TCGA_t_cells$bcr_patient_barcode <- rownames(TCGA_t_cells)

TCGA_t_cells_f <- TCGA_t_cells
TCGA_t_cells_f$t_cells_quartile.1 <- TCGA_t_cells_f$t_cells_quartile
# TCGA_t_cells_f$t_cells_quartile.1 <- gsub(pattern = "3", replacement = "2", x = TCGA_t_cells_f$t_cells_quartile.1)
table(TCGA_t_cells_f$t_cells_quartile.1)
TCGA_t_cells_f$bcr_patient_barcode <- TCGA_t_cells$Input.Sample

luad_tcga1_t_cells <- left_join(tcga_meta, TCGA_t_cells_f, by = "bcr_patient_barcode")

# Subset to only late stage
# luad_tcga1_t_cells <- filter(luad_tcga1_t_cells, ajcc_pathologic_tumor_stage == "Stage IIIA" | ajcc_pathologic_tumor_stage == "Stage IIIB" | ajcc_pathologic_tumor_stage == "Stage IV")
# table(luad_tcga1_t_cells$ajcc_pathologic_tumor_stage)

# Use only quantile 1 and 4
# luad_tcga1_t_cells <- filter(luad_tcga1_t_cells, t_cells_quartile.1 == "1" | t_cells_quartile.1 == "4")

# pdf(file = paste(dir, "plot_out/NI10/Tcell_OS.pdf", sep = ""))
survminer::ggsurvplot(
    fit = survival::survfit(survival::Surv((OS.time/365), OS) ~ t_cells_quartile.1, data = luad_tcga1_t_cells), 
    xlab = "Years",
    ylab = "Overall survival probability",
    legend.title = "Tcell Population Quartile",
    censor = TRUE,
    conf.int = FALSE,
    pval = TRUE,
    legend = c(0.8, 0.8),
    palette = rev(RColorBrewer::brewer.pal(n = 4, name = "RdBu")))
# dev.off()

fit <- survival::survfit(survival::Surv((OS.time/365), OS) ~ t_cells_quartile.1, data = luad_tcga1_t_cells)

surv_pvalue(fit)

# summary(survival::survfit(survival::Surv((OS.time/365), OS) ~  t_cells_quartile.1, data = luad_tcga1_t_cells), 
#         times = 3)
# 
# survminer::ggsurvplot(
#     fit = survival::survfit(survival::Surv((PFI.time/365), PFI) ~ t_cells_quartile.1, data = luad_tcga1_t_cells), 
#     xlab = "Years",
#     ylab = "Progression free interval probability",
#     legend.title = "Tcell Population Quartile",
#     censor = TRUE,
#     conf.int = FALSE,
#     pval = TRUE,
#     palette = c("#330066", "#CCCC00"))
# 
# summary(survival::survfit(survival::Surv((PFI.time/365), PFI) ~  t_cells_quartile.1, data = luad_tcga1_t_cells), 
#         times = 3)
```
```{r}
# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = luad_tcga1_t_cells$OS.time, event = luad_tcga1_t_cells$OS)
surv_object

luad_tcga1_t_cells$t_cells_quartile.1 <- factor(luad_tcga1_t_cells$t_cells_quartile.1)

# 
# # Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ t_cells_quartile.1,
                   data = luad_tcga1_t_cells, ties = 'exact')
ggforest(fit.coxph, data = luad_tcga1_t_cells)

summary(fit.coxph)
```

